name: Release LaTeX PDF
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume.tex
            resume_zh.tex

      - name: Check PDF files
        run: |
          file resume.pdf | grep -q ' PDF '
          file resume_zh.pdf | grep -q ' PDF '

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            resume.pdf
            resume_zh.pdf
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}